Projek_Youtube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('youtubeapp.urls'))
]

youtubeapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'youtubeapp'
urlpatterns = [
    path('', views.index, name="index"),
    path('video/<int:video_id>', views.show, name="show"),
    path('search/', views.search, name="search"),
    path('upload/', views.upload, name="upload"),
    path('upload_selesai/', views.upload_selesai, name="upload_selesai"),
    path('trending/', views.trending, name="trending")
]

youtubeapp/models.py
from django.db import models

# Create your models here.
class Video(models.Model):
    judul = models.CharField(max_length=200, default='')
    url_video = models.CharField(max_length=200, default='')
    author = models.CharField(max_length=200, default='')
    waktu_upload = models.DateTimeField('Waktu Upload')
    foto_author = models.CharField(max_length=200, default='')
    deskripsi = models.TextField(default='')
    thumbnail = models.CharField(max_length=200, default='')
    embed = models.CharField(max_length=200, default='')
    jumlah_view = models.IntegerField(default=0)

    def __str__(self):
        return self.judul

youtubeapp/views.py
from django.shortcuts import render, HttpResponse
from .models import Video
from datetime import datetime
import random

# Create your views here.
def index(request):
    kumpulan_video = Video.objects.all()
    kirim = {
        'kumpulan_video' : kumpulan_video,
    }
    return render(request, 'youtubeapp/index.html', kirim)

def show(request, video_id):
    video = Video.objects.get(pk = video_id)
    tambah = video.jumlah_view
    tambah += 1
    video.jumlah_view = tambah
    video.save()

    for konten in Video.objects.all():
        if konten != video:
            random_video = konten
            random_number = random.randint(0,3)
            if random_number == 1:
                break

    kirim = {
        'video' : video,
        'random_video' : random_video
    }
    return render(request, 'youtubeapp/show.html', kirim)

def search(request):
    kata = request.POST['cari']
    hasil_cari = Video.objects.filter(judul__icontains = kata)
    if len(hasil_cari) != 0:
        message = '2'
    else:
        message = '3'

    kirim = {
        'kumpulan_video' : hasil_cari,
        'message' : message
    }
    return render(request, 'youtubeapp/index.html', kirim)

def upload(request):
    return render(request, 'youtubeapp/upload.html', {})

def upload_selesai(request):
    video_baru = Video(
        judul = request.POST['judul'],
        url_video = request.POST['url_video'],
        author = request.POST['author'],
        waktu_upload = datetime.now(),
        foto_author = request.POST['foto_author'],
        deskripsi = request.POST['deskripsi'],
        thumbnail = request.POST['thumbnail'],
        embed = request.POST['embed'],
        jumlah_view = 0
    )
    video_baru.save()
    # return render(request, 'youtubeapp/index.html', {})
    return HttpResponse('Success')

def trending(request):
    trend = Video.objects.all().order_by('-jumlah_view', 'judul')[:4]
    kirim = {
        'kumpulan_video' : trend,
        'message' : '1'
    }
    return render(request, 'youtubeapp/index.html', kirim)

youtubeapp/templates/youtubeapp/base.html
<!DOCTYPE html>

<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static 'img/title/favicon.png' %}"/>
  </head>

  <body>
      {% include 'youtubeapp/navbar.html' %}
      

      {% block content %} 
      {% endblock%}

    <script src="{% static 'js/bootstrap.js' %}"></script>
  </body>
</html>

youtubeapp/templates/youtubeapp/index.html
{% extends 'youtubeapp/base.html' %}

{% block title %}Youtube{% endblock %}
{% load static %}
{% block content %}
<header>
    <div class="container-fluid align-items-center text-center">
        <div class="row">
            <!-- space kosong di bawah header utama -->
            <div class="header_bawah">
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="ver_header col-md-1">
                <div class="row justify-content-center align-items-center">
                    <div class="logo_ver col-md-12 justify-content-center align-items-center text-center">
                        <a href="{% url 'youtubeapp:index' %}"><img  class="image_logo" src="{% static 'img/title/house.png' %}" alt=""></a>
                        <a class="logo-home-verbar " href="{% url 'youtubeapp:index' %}"><h3>Home</h3></a>
                    </div>
                    <div class="logo_ver col-md-12 justify-content-center align-items-center text-center">
                        <a href="{% url 'youtubeapp:upload' %}"><img  class="image_logo" src="{% static 'img/title/kamera.png' %}" alt=""></a>
                        <a class="logo-home-verbar " href="{% url 'youtubeapp:upload' %}"><h3>Upload</h3></a>
                    </div>
                    <div class="logo_ver col-md-12  justify-content-center align-items-center text-center">
                        <a href="{% url 'youtubeapp:trending' %}"><img  class="image_logo" src="{% static 'img/title/trending.png' %}" alt=""></a>
                        <a class="logo-home-verbar " href="{% url 'youtubeapp:trending' %}"><h3>Trending</h3></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-11 playlist">Playlist
                {% if message == '1' %}
                 (Trending)
                {% elif message == '2' %}
                 (Search Result)
                {% elif message == '3' %}
                 (Search Result)<br /><br />Video Not Found
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-11">
                <div class="container-fluid">
                    <div class="row">
                        {% for video in kumpulan_video %}
                        <div class="col-3 kolom_video">
                            <a href="{% url 'youtubeapp:show' video.id%}">
                                <img src="{{video.thumbnail}}" class="konten_video">
                            </a>
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-2 kolom_foto_author">
                                        <div class="bungkus-foto">
                                            <img class="foto_author" src="{{video.foto_author}}">
                                        </div>
                                    </div>
                                    <div class="col-10 judul_dan_author">
                                        <div class="col-12 judul_utama">{{video.judul}}</div>
                                        <div class="col-12 author">{{video.author}}</div>
                                        <div class="col-12 waktu_upload">{{video.jumlah_view}} Views<br />{{video.waktu_upload}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

youtubeapp/templates/youtubeapp/navbar.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>
            Home
        </title>
        {% load static %}
        <link rel='stylesheet' href="{% static 'CSS/bootstrap.min.css' %}">
        <link rel='stylesheet' href="{% static 'CSS/main.css' %}">
    </head>
    <body>
        <header>
            <div class="header container-fluid ">
                <div class="row align-items-center text-center">
                    <div class="col-md-2">
                        <div>
                            <a href="{% url 'youtubeapp:index' %}"><img class="image_home" src="{% static 'img/title/youtube.png' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="bar_search col-md-8">
                        <nav class="navbar">

                            <form class="form-inline" method="POST" action="{% url 'youtubeapp:search'%}">
                                {% csrf_token %}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1" name="cari">   
                                    </div>
                                        <button type="submit"><i class="fa fa-search"></i><img href="/" class="image_logo" src="{% static 'img/title/search.png' %}" alt=""></button>
                                </div>
                            </form>

                        </nav>
                    </div>
                    <div class="bar_log col-md-2">
                        <a href="{% url 'youtubeapp:upload' %}"><img class="image_logo" src="{% static 'img/title/kamera.png' %}" alt=""></a>
                        <img href="/" class="image_logo" src="{% static 'img/title/lonceng.png' %}" alt="">
                        <img href="/" class="image_logo" src="{% static 'img/title/account.png' %}" alt="">
                    </div>
                </div>
            </div>
        </header>

youtubeapp/templates/youtubeapp/show.html
{% extends 'youtubeapp/base.html' %}

{% block title %}Youtube{% endblock %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 tampilan_video">
                <div>
                    <iframe width="100%" height="450" src="{{video.embed}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div> 
            <div class="col-md-4 tampilan_video_pinggir justify-content-center align-items-center">
                <div class="up_next">
                    Up Next
                </div>
                <div>
                    <a href="{% url 'youtubeapp:show' random_video.id %}">
                        <img src="{{random_video.thumbnail}}" class="konten_video">
                    </a>
                </div>
                <div class="col-md-12 video_kecil">
                    <div class="judul_utama">{{random_video.judul}}</div>
                    <div class="author">{{random_video.author}}</div>
                    <div class="waktu_upload">{{random_video.jumlah_view}} Views<br />{{random_video.waktu_upload}}</div>
                </div>
            </div>
        </div>  
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 tampilan_akun">
                <h5 class="judul">
                    {{video.judul}}
                </h5>
                <div class="row tanggal_padding justify-content-center align-items-center">
                    <div class="col-md-8 justify-content-center align-items-center">
                        <ul class="header-nav list-unstyled">
                            <li>
                                <p class="waktu_upload_show"href="/">{{video.jumlah_view}} Views</p>
                            </li>
                            <li>
                                <p class="waktu_upload_show">{{video.waktu_upload}}</p>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 justify-content-center align-items-center text-right">
                        <ul class="header-nav list-unstyled">
                            <li>
                                <img href="/" class="image_logo" src="{% static 'img/title/like.png' %}" alt="">
                            </li>
                            <li>
                                <p class="waktu_upload_show"href="/">{{video.jumlah_view}} Likes</p>
                            </li>
                            <li>
                                <img href="/" class="image_logo" src="{% static 'img/title/dislike.png' %}" alt="">
                            </li> 
                            <li>
                                <p class="waktu_upload_show">0 Dislike</p>
                            </li>
                        </ul>
                    </div>
                </div>
                    <div class="line"></div>
                    <div class="container-fluid">
                        <div class="row justify-content-center align-items-center">
                            <div class="col-1 kolom_foto_author_show justify-content-center align-items-center">
                                <div class="bungkus-foto_show">
                                    <img class="foto_author" src="{{video.foto_author}}">
                                </div>
                            </div>
                            <div class="col-11 author_deskripsi">
                                <div class="col-12 author_show">
                                    {{video.author}}
                                </div>
                                <div>
                                    <p class="desc-video">99K Subscriber</p>
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center align-items-center mar">
                            <div class="col-1 justify-content-center align-items-center">
                            </div>
                            <div class="col-11 author_deskripsi">
                                <p class="desc-video">{{video.deskripsi}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col-4"></div>
        </div>
    </div>
{% endblock %}

youtubeapp/templates/youtubeapp/upload.html
{% extends 'youtubeapp/base.html' %}

{% block title %}Youtube{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6 halaman_upload_form">
            <h2 class=judul_upload>Upload Your Video Here</h2>
            <form method="POST" action="{% url 'youtubeapp:upload_selesai' %}">
                {% csrf_token %}
                <label for="judul">Judul</label><br />
                <input type="text" name="judul" id="judul" class="input_box"><br /><br />
    
                <label for="url_video">URL Video</label><br />
                <input type="text" name="url_video" id="url_video" class="input_box"><br /><br />
    
                <label for="author">Author</label><br />
                <input type="text" name="author" id="author" class="input_box"><br /><br />
    
                <label for="foto_author">Foto Author</label><br />
                <input name="foto_author" id="foto_author" class="input_box"><br /><br />
    
                <label for="deskripsi">Deskripsi</label><br />
                <textarea rows="8" cols="45" type="text" name="deskripsi" id="deskripsi" class="input-box"></textarea><br /><br />
    
                <label for="thumbnail">Thumbnail</label><br />
                <input type="text" name="thumbnail" id="thumbnail" class="input_box"><br /><br />
    
                <label for="embed">Embed</label><br />
                <input type="text" name="embed" id="embed" class="input_box"><br /><br/>

                <button type="submit" class="btn btn-danger">Upload</button>
            </form>
            <div class="col-3"></div>
        </div>
    </div>
</div>
{% endblock %}

youtubeapp/templates/youtubeapp/vertical_navbar.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>
            Home
        </title>
        {% load static %}
        <link rel='stylesheet' href="{% static 'CSS/bootstrap.min.css' %}">
        <link rel='stylesheet' href="{% static 'CSS/main.css' %}">
    </head>
    <body>